import { readFile, readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { AGENTS_END, AGENTS_START } from '../constants.js';
import { atomicWrite, backupFile, ensureDir, pathExists, readJson, removeIfExists, writeJson } from '../lib/fs.js';
import { upsertManagedBlock, removeManagedBlock } from '../lib/managed-block.js';
import {
  DEFAULT_MODEL_MAP,
  PROFILE_DEFINITIONS,
  ROLE_METADATA,
  globalPaths,
  type ProfileId,
  type RoleId,
} from '../config.js';
import { GLOBAL_AGENTS_BLOCK } from '../templates.js';

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function roleToml(role: Exclude<RoleId, 'main'>): string {
  const config = DEFAULT_MODEL_MAP.roles[role];
  const model = DEFAULT_MODEL_MAP.models[config.model].provider_model;
  const metadata = ROLE_METADATA[role];
  return [
    `name = ${tomlString(metadata.name)}`,
    `description = ${tomlString(metadata.description)}`,
    `developer_instructions = ${tomlString(metadata.developer_instructions)}`,
    `model = ${tomlString(model)}`,
    `model_reasoning_effort = ${tomlString(config.reasoning)}`,
    `sandbox_mode = ${tomlString(metadata.sandbox_mode)}`,
    'model_verbosity = "low"',
    'model_reasoning_summary = "concise"',
    'tool_output_token_limit = 4000',
    '',
    '[agents]',
    'max_depth = 0',
    'max_threads = 1',
    'interrupt_message = false',
    '',
  ].join('\n');
}

function mainProfile(): string {
  return [
    '# Generated by Agent Router. Launch with: codex --profile agent-router',
    'model = "gpt-5.6-luna"',
    'model_reasoning_effort = "low"',
    'model_verbosity = "low"',
    'model_reasoning_summary = "concise"',
    'model_auto_compact_token_limit = 64000',
    'model_auto_compact_token_limit_scope = "total"',
    'tool_output_token_limit = 4000',
    'allow_login_shell = false',
    '',
    '[agents]',
    'max_threads = 2',
    'max_depth = 1',
    'job_max_runtime_seconds = 7200',
    'interrupt_message = false',
    '',
    '[shell_environment_policy]',
    'inherit = "all"',
    '',
    '[shell_environment_policy.set]',
    'AGENT_ROUTER_ACTIVE = "1"',
    '',
  ].join('\n');
}

function childRoles(roles: RoleId[]): Array<Exclude<RoleId, 'main'>> {
  return roles.filter((role): role is Exclude<RoleId, 'main'> => role !== 'main');
}

async function managedGlobalAgents(path: string): Promise<string> {
  const existing = (await pathExists(path)) ? await readFile(path, 'utf8') : '';
  return upsertManagedBlock(existing, { start: AGENTS_START, end: AGENTS_END, body: GLOBAL_AGENTS_BLOCK });
}

interface GlobalConfigRecord {
  schema_version: 1;
  provider: 'codex';
  installed_profiles: ProfileId[];
  enabled_roles: RoleId[];
  codex_home: string;
}

export async function codexSetup(options: {
  apply: boolean;
  dryRun: boolean;
  profile: ProfileId;
  roles: RoleId[];
}): Promise<Record<string, unknown>> {
  const paths = globalPaths();
  const requiredRoles = PROFILE_DEFINITIONS[options.profile].roles;
  const missingRequired = requiredRoles.filter((role) => !options.roles.includes(role));
  if (missingRequired.length) throw new Error(`Profile ${options.profile} requires roles: ${missingRequired.join(', ')}`);
  const agentsPath = resolve(paths.codexHome, 'AGENTS.md');
  const overridePath = resolve(paths.codexHome, 'AGENTS.override.md');
  const configPath = resolve(paths.root, 'config.yaml');
  const existingConfig = (await pathExists(configPath)) ? await readJson<GlobalConfigRecord>(configPath) : null;
  const installedProfiles = [...new Set([...(existingConfig?.installed_profiles ?? []), options.profile])];
  const installedRoles = [...new Set([...(existingConfig?.enabled_roles ?? ['main']), ...options.roles])] as RoleId[];
  const files: Array<{ path: string; content: string }> = [
    { path: resolve(paths.codexHome, 'agent-router.config.toml'), content: mainProfile() },
    { path: agentsPath, content: await managedGlobalAgents(agentsPath) },
  ];
  for (const role of childRoles(options.roles)) {
    files.push({ path: resolve(paths.codexHome, 'agents', `agent-router-${role.replaceAll('_', '-')}.toml`), content: roleToml(role) });
  }
  const warnings: string[] = [];
  if (await pathExists(overridePath)) warnings.push(`${overridePath} exists and takes precedence over ${agentsPath}; merge the Agent Router block into the override or remove the override.`);
  const plan = {
    provider: 'codex',
    apply: options.apply,
    profile: options.profile,
    profile_description: PROFILE_DEFINITIONS[options.profile].description,
    roles: options.roles,
    installed_profiles: installedProfiles,
    installed_roles: installedRoles,
    agent_router_home: paths.root,
    codex_home: paths.codexHome,
    files: files.map(({ path }) => path),
    work_repository_writes: [] as string[],
    warnings,
    created_at: new Date().toISOString(),
  };
  if (options.dryRun || !options.apply) return { ...plan, applied: false };

  await ensureDir(paths.root);
  await ensureDir(paths.projects);
  await ensureDir(paths.bindings);
  await ensureDir(paths.contexts);
  await ensureDir(paths.reviewPacks);
  await ensureDir(paths.logs);
  await ensureDir(paths.backups);
  const backups: Array<{ path: string; backup: string | null }> = [];
  for (const file of files) {
    backups.push({ path: file.path, backup: await backupFile(file.path) });
    await atomicWrite(file.path, file.content);
  }
  await writeJson(configPath, {
    schema_version: 1,
    provider: 'codex',
    installed_profiles: installedProfiles,
    enabled_roles: installedRoles,
    codex_home: paths.codexHome,
  } satisfies GlobalConfigRecord);
  await writeJson(resolve(paths.root, 'last-setup.json'), { ...plan, backups, applied_at: new Date().toISOString() });
  return { ...plan, applied: true, backups };
}

export async function codexSetupStatus(): Promise<Record<string, unknown>> {
  const paths = globalPaths();
  const profilePath = resolve(paths.codexHome, 'agent-router.config.toml');
  const agentsPath = resolve(paths.codexHome, 'AGENTS.md');
  const overridePath = resolve(paths.codexHome, 'AGENTS.override.md');
  const agentsDir = resolve(paths.codexHome, 'agents');
  const agents = (await pathExists(agentsDir))
    ? (await readdir(agentsDir)).filter((name) => name.startsWith('agent-router-') && name.endsWith('.toml')).sort()
    : [];
  const agentsText = (await pathExists(agentsPath)) ? await readFile(agentsPath, 'utf8') : '';
  const globalConfigPath = resolve(paths.root, 'config.yaml');
  return {
    provider: 'codex',
    agent_router_home: paths.root,
    codex_home: paths.codexHome,
    profile_path: profilePath,
    profile_exists: await pathExists(profilePath),
    global_agents_path: agentsPath,
    global_agents_managed: agentsText.includes(AGENTS_START) && agentsText.includes(AGENTS_END),
    global_override_path: overridePath,
    global_override_exists: await pathExists(overridePath),
    agents,
    global_config: (await pathExists(globalConfigPath)) ? await readJson(globalConfigPath) : null,
    last_setup: (await pathExists(resolve(paths.root, 'last-setup.json'))) ? await readJson(resolve(paths.root, 'last-setup.json')) : null,
  };
}

export async function codexSetupRollback(): Promise<Record<string, unknown>> {
  const paths = globalPaths();
  const statePath = resolve(paths.root, 'last-setup.json');
  if (!(await pathExists(statePath))) throw new Error('No setup rollback state exists');
  const state = await readJson<{ backups: Array<{ path: string; backup: string | null }> }>(statePath);
  const restored: string[] = [];
  const removed: string[] = [];
  for (const item of state.backups) {
    if (item.backup && await pathExists(item.backup)) {
      await atomicWrite(item.path, await readFile(item.backup));
      restored.push(item.path);
    } else {
      await removeIfExists(item.path);
      removed.push(item.path);
    }
  }
  return { restored, removed };
}

export async function removeGlobalAgentsManagedBlock(): Promise<Record<string, unknown>> {
  const path = resolve(globalPaths().codexHome, 'AGENTS.md');
  if (!(await pathExists(path))) return { path, changed: false };
  const existing = await readFile(path, 'utf8');
  const updated = removeManagedBlock(existing, AGENTS_START, AGENTS_END);
  if (updated === existing) return { path, changed: false };
  await atomicWrite(path, updated);
  return { path, changed: true };
}
