import { readFile, readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { AGENTS_END, AGENTS_START, VERSION } from '../constants.js';
import { atomicWrite, backupFile, ensureDir, pathExists, readJson, removeIfExists, writeJson } from '../lib/fs.js';
import { upsertManagedBlock, removeManagedBlock } from '../lib/managed-block.js';
import {
  DEFAULT_MODEL_MAP,
  ROLE_METADATA,
  allInstallableRoles,
  globalPaths,
  type RoleId,
} from '../config.js';
import { GLOBAL_AGENTS_BLOCK } from '../templates.js';

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function roleToml(role: Exclude<RoleId, 'main'>): string {
  const config = DEFAULT_MODEL_MAP.roles[role];
  const model = DEFAULT_MODEL_MAP.models[config.model].provider_model;
  const metadata = ROLE_METADATA[role];
  return [
    `name = ${tomlString(metadata.name)}`,
    `description = ${tomlString(metadata.description)}`,
    `developer_instructions = ${tomlString(metadata.developer_instructions)}`,
    `model = ${tomlString(model)}`,
    `model_reasoning_effort = ${tomlString(config.reasoning)}`,
    `sandbox_mode = ${tomlString(metadata.sandbox_mode)}`,
    'model_verbosity = "low"',
    'model_reasoning_summary = "concise"',
    'tool_output_token_limit = 4000',
    '',
    '[agents]',
    'max_depth = 0',
    'max_threads = 1',
    'interrupt_message = false',
    '',
  ].join('\n');
}

function mainProfile(): string {
  return [
    '# Generated by Agent Router. Launch with: codex --profile agent-router',
    'model = "gpt-5.6-luna"',
    'model_reasoning_effort = "low"',
    'model_verbosity = "low"',
    'model_reasoning_summary = "concise"',
    'model_auto_compact_token_limit = 64000',
    'model_auto_compact_token_limit_scope = "total"',
    'tool_output_token_limit = 4000',
    'allow_login_shell = false',
    '',
    '[agents]',
    'max_threads = 2',
    'max_depth = 1',
    'job_max_runtime_seconds = 7200',
    'interrupt_message = false',
    '',
    '[shell_environment_policy]',
    'inherit = "all"',
    '',
    '[shell_environment_policy.set]',
    'AGENT_ROUTER_ACTIVE = "1"',
    '',
  ].join('\n');
}

function childRoles(roles: RoleId[]): Array<Exclude<RoleId, 'main'>> {
  return roles.filter((role): role is Exclude<RoleId, 'main'> => role !== 'main');
}

async function managedGlobalAgents(path: string): Promise<string> {
  const existing = (await pathExists(path)) ? await readFile(path, 'utf8') : '';
  return upsertManagedBlock(existing, { start: AGENTS_START, end: AGENTS_END, body: GLOBAL_AGENTS_BLOCK });
}

interface LegacyGlobalConfigRecord {
  schema_version: 1;
  provider: 'codex';
  installed_version?: string;
  installed_roles?: RoleId[];
  installed_profiles?: string[];
  enabled_roles?: RoleId[];
  codex_home: string;
}

interface GlobalConfigRecord {
  schema_version: 1;
  provider: 'codex';
  installed_version: string;
  installed_roles: RoleId[];
  codex_home: string;
}

function roleFilePath(role: Exclude<RoleId, 'main'>): string {
  return resolve(globalPaths().codexHome, 'agents', `agent-router-${role.replaceAll('_', '-')}.toml`);
}

function expectedRoleConfig(role: Exclude<RoleId, 'main'>): { model: string; reasoning: string } {
  const config = DEFAULT_MODEL_MAP.roles[role];
  return {
    model: DEFAULT_MODEL_MAP.models[config.model].provider_model,
    reasoning: config.reasoning,
  };
}

function roleConfigIsValid(role: Exclude<RoleId, 'main'>, content: string): boolean {
  const expected = expectedRoleConfig(role);
  return content.includes(`model = ${JSON.stringify(expected.model)}`)
    && content.includes(`model_reasoning_effort = ${JSON.stringify(expected.reasoning)}`)
    && content.includes(`name = ${JSON.stringify(ROLE_METADATA[role].name)}`)
    && content.includes(`sandbox_mode = ${JSON.stringify(ROLE_METADATA[role].sandbox_mode)}`);
}

export async function codexSetup(options: {
  apply: boolean;
  dryRun: boolean;
}): Promise<Record<string, unknown>> {
  const paths = globalPaths();
  const agentsPath = resolve(paths.codexHome, 'AGENTS.md');
  const overridePath = resolve(paths.codexHome, 'AGENTS.override.md');
  const configPath = resolve(paths.root, 'config.yaml');
  const existingConfig = (await pathExists(configPath)) ? await readJson<LegacyGlobalConfigRecord>(configPath) : null;
  const installedRoles = allInstallableRoles();
  const legacyProfileMetadata = Array.isArray(existingConfig?.installed_profiles);
  const config: GlobalConfigRecord = {
    schema_version: 1,
    provider: 'codex',
    installed_version: VERSION,
    installed_roles: installedRoles,
    codex_home: paths.codexHome,
  };
  const configContent = `${JSON.stringify(config, null, 2)}\n`;
  const files: Array<{ path: string; content: string }> = [
    { path: resolve(paths.codexHome, 'agent-router.config.toml'), content: mainProfile() },
    { path: agentsPath, content: await managedGlobalAgents(agentsPath) },
    { path: configPath, content: configContent },
  ];
  for (const role of childRoles(installedRoles)) {
    files.push({ path: roleFilePath(role), content: roleToml(role) });
  }
  const warnings: string[] = [];
  if (await pathExists(overridePath)) warnings.push(`${overridePath} exists and takes precedence over ${agentsPath}; merge the Agent Router block into the override or remove the override.`);
  const plan = {
    provider: 'codex',
    apply: options.apply,
    installed_roles: installedRoles,
    installed_version: config.installed_version,
    legacy_profile_metadata_removed: legacyProfileMetadata,
    agent_router_home: paths.root,
    codex_home: paths.codexHome,
    files: files.map(({ path }) => path),
    work_repository_writes: [] as string[],
    warnings,
    created_at: new Date().toISOString(),
  };
  if (options.dryRun || !options.apply) return { ...plan, applied: false };

  await ensureDir(paths.root);
  await ensureDir(paths.projects);
  await ensureDir(paths.bindings);
  await ensureDir(paths.contexts);
  await ensureDir(paths.reviewPacks);
  await ensureDir(paths.logs);
  await ensureDir(paths.backups);
  const backups: Array<{ path: string; backup: string | null }> = [];
  for (const file of files) {
    const existing = (await pathExists(file.path)) ? await readFile(file.path, 'utf8') : null;
    if (existing === file.content) continue;
    backups.push({ path: file.path, backup: await backupFile(file.path) });
    await atomicWrite(file.path, file.content);
  }
  await writeJson(resolve(paths.root, 'last-setup.json'), { ...plan, backups, applied_at: new Date().toISOString() });
  return { ...plan, applied: true, backups };
}

export async function codexSetupStatus(): Promise<Record<string, unknown>> {
  const paths = globalPaths();
  const profilePath = resolve(paths.codexHome, 'agent-router.config.toml');
  const agentsPath = resolve(paths.codexHome, 'AGENTS.md');
  const overridePath = resolve(paths.codexHome, 'AGENTS.override.md');
  const agentsDir = resolve(paths.codexHome, 'agents');
  const agents = (await pathExists(agentsDir))
    ? (await readdir(agentsDir)).filter((name) => name.startsWith('agent-router-') && name.endsWith('.toml')).sort()
    : [];
  const agentsText = (await pathExists(agentsPath)) ? await readFile(agentsPath, 'utf8') : '';
  const globalConfigPath = resolve(paths.root, 'config.yaml');
  const globalConfig = (await pathExists(globalConfigPath))
    ? await readJson<LegacyGlobalConfigRecord>(globalConfigPath)
    : null;
  const roleStatuses: Record<string, { path: string; exists: boolean; valid: boolean; model: string; reasoning: string }> = {};
  for (const role of childRoles(allInstallableRoles())) {
    const path = roleFilePath(role);
    const exists = await pathExists(path);
    const content = exists ? await readFile(path, 'utf8') : '';
    const expected = expectedRoleConfig(role);
    roleStatuses[role] = { path, exists, valid: exists && roleConfigIsValid(role, content), ...expected };
  }
  const mainContent = (await pathExists(profilePath)) ? await readFile(profilePath, 'utf8') : '';
  return {
    provider: 'codex',
    agent_router_home: paths.root,
    codex_home: paths.codexHome,
    profile_path: profilePath,
    profile_exists: await pathExists(profilePath),
    global_agents_path: agentsPath,
    global_agents_managed: agentsText.includes(AGENTS_START) && agentsText.includes(AGENTS_END),
    global_override_path: overridePath,
    global_override_exists: await pathExists(overridePath),
    agents,
    installed_roles: globalConfig?.installed_roles ?? globalConfig?.enabled_roles ?? [],
    role_statuses: roleStatuses,
    main_profile_valid: mainContent.includes('model = "gpt-5.6-luna"') && mainContent.includes('model_reasoning_effort = "low"'),
    global_config: globalConfig,
    last_setup: (await pathExists(resolve(paths.root, 'last-setup.json'))) ? await readJson(resolve(paths.root, 'last-setup.json')) : null,
  };
}

export async function codexSetupRollback(): Promise<Record<string, unknown>> {
  const paths = globalPaths();
  const statePath = resolve(paths.root, 'last-setup.json');
  if (!(await pathExists(statePath))) throw new Error('No setup rollback state exists');
  const state = await readJson<{ backups: Array<{ path: string; backup: string | null }> }>(statePath);
  const restored: string[] = [];
  const removed: string[] = [];
  for (const item of state.backups) {
    if (item.backup && await pathExists(item.backup)) {
      await atomicWrite(item.path, await readFile(item.backup));
      restored.push(item.path);
    } else {
      await removeIfExists(item.path);
      removed.push(item.path);
    }
  }
  return { restored, removed };
}

export async function removeGlobalAgentsManagedBlock(): Promise<Record<string, unknown>> {
  const path = resolve(globalPaths().codexHome, 'AGENTS.md');
  if (!(await pathExists(path))) return { path, changed: false };
  const existing = await readFile(path, 'utf8');
  const updated = removeManagedBlock(existing, AGENTS_START, AGENTS_END);
  if (updated === existing) return { path, changed: false };
  await atomicWrite(path, updated);
  return { path, changed: true };
}
